### ISSUE TITLE
Suggestion: Similar to: `….darkThemesFirst` this setting would be useful: "The currently active theme type first"

### ISSUE THREAD

**Issue by schittli** [kamenminkov/favourite-themes#2]
Hello

At night I love this setting: `favouriteThemes.darkThemesFirst` so one is not suddenly strongly blinded.
But during the day the setting is tedious, because then one always has to navigate to the light themes first.

Therefore it would be awesome if there is a setting similar to `favouriteThemes.darkThemesFirst` but that works like this:

- When a dark theme is active, dark themes are shown first
- If a light theme is active, light themes are displayed first
 
Thanks a lot, kind regards,
Thomas

**Comment by kamenminkov** [comment]
Haven't thought about it, but it actually makes a lot of sense!
Will think about how to do it (in the sense of making the new setting work with the existing one instead of clashing with it) and will have a go at it when I have a bit of time.

**Comment by kamenminkov** [comment]
@schittli Sorry I couldn't get back to you earlier. Was busy during the week and didn't have much time outside of it either.

Did some work on that and I have progress.

Let me just double check if I understand you correctly. So if you have the following pinned themes (with the first one currently selected)

```json
{
  "favouriteThemes.pinnedThemes": [
    "Light3",
    "Light2",
    "Dark2",
    "Light1",
    "Dark1"
  ]
}
```

... that should produce a picker as follows:

```
[x] Light3
[x] Light2
[x] Light1
[x] Dark2
[x] Dark1
[ ] Light4
[ ] Light5
[ ] Light6
[ ] Dark3
[ ] Dark4
```

Similarly, if you currently have a dark theme...

```json
{
  "favouriteThemes.pinnedThemes": [
    "Dark2",
    "Light3",
    "Light1",
    "Light2",
    "Dark1"
  ]
}
```

... the picker should look like this:

```
[x] Dark2
[x] Dark1
[x] Light3
[x] Light1
[x] Light2
[ ] Dark3
[ ] Dark4
[ ] Light4
[ ] Light5
[ ] Light6
```

Is that how you'd expect it to work?

Of course the themes would be shuffled only initially (for the sake of the example) - before you enable the new setting. Sorting happens when the picker is shown, and once you select a new theme, that same order is persisted in your settings.

If that looks okay to you, I'll just test something tomorrow (regarding sorting within those groups) and should be able to push an update.

Talking about switching between dark and light themes gave me a hint about working on some sort of scheduling - what do you think of that? I.e. "switch to the first light theme every morning at 09:00 and switch to the first dark theme every evening at 19:00" with the hours being customisable. It would work nicely with `"favouriteThemes.showThemesOfCurrentTypeFirst"` (the new setting regarding the current issue) or without it and shouldn't be too difficult to implement.

**Comment by kamenminkov** [comment]
Pushed an update that includes this fix. If it's not quite what you were thinking, feel free to open another issue.
